### ISSUE TITLE
`asdf where direnv` does not do the right thing when using `direnv system`

### ISSUE THREAD

**Issue by glasserc** [asdf-community/asdf-direnv#103]
I'm trying to bootstrap a new laptop and having trouble getting my admittedly idiosyncratic setup to work. (Previously: https://github.com/asdf-community/asdf-direnv/issues/55.) In the past I have installed `direnv` at the system level using e.g. apt and setting `asdf global direnv system`. Since we hook into `direnv` on shell startup, it makes sense to me that we have a system-level one rather than switching around as we move to different directories. (direnv definitely dispatches to asdf, so having asdf manage direnv too feels a little circular to me.)

Switching into a new directory using this configuration, I get:

```
direnv: loading ~/src/drew-aligner/.envrc
direnv: using asdf
direnv: Error generating asdf cached envrc
```

I tried adding `set -x` to the top of `command.bash` following debugging advice in https://github.com/asdf-community/asdf-direnv/issues/102 and the last few lines are as follows:

```
++ shopt -s gnu_errfmt
++ shopt -s nullglob
++ shopt -s extglob
++ direnv=/usr/bin/direnv
++ DIRENV_LOG_FORMAT='direnv: %s'
++ direnv_config_dir=/home/ethan/.config/direnv
++ export DIRENV_IN_ENVRC=1
++ DIRENV_IN_ENVRC=1
+ case "$1" in
+ _asdf_cached_envrc
+ local dump_dir tools_file tools_cksum env_file
++ asdf where direnv
+ dump_dir='System version is selected/env'
direnv: Error generating asdf cached envrc
```

Indeed it seems that `asdf where direnv` prints `System version is selected`, which means that this line does not do what I think it's supposed to:

https://github.com/asdf-community/asdf-direnv/blob/6426f1336c7d06d1a12404b1df349a3ecf8d8490/lib/commands/command.bash#L21

Doing `asdf global direnv 2.30.3` causes `direnv reload` to work OK.

See also https://github.com/asdf-vm/asdf/issues/1130, which also poses an issue when trying to use `direnv system`. (To work around that, I did `asdf install direnv latest`, although I don't intend for it to be used.)

**Comment by jfly** [comment]
Interesting. I wonder if the goal here is to put the cached envrc files in a place that's specific to the current version of direnv (so if we switch versions of direnv we automatically need to regenerate all the cached envrc files), or if that's just a convenient place to put the files.

We could probably put together a workaround for this, we'd just have to find some other place to put these cached files. (We might even be able to do this unconditionally, rather than doing something special when you've got system direnv selected). I just don't know if I'm actually understanding this all correctly, or if this is something we even would want to support or not. I'd defer to @vic on this.

**Comment by glasserc** [comment]
I can add that on my last laptop, `asdf where direnv` produces `/home/ethan/.config/asdf/installs/direnv/system`, whose `env` subdirectory contains about 21 files.

**Comment by vic** [comment]
looking at the debugging output I believe we could simply use `direnv_config_dir` and place cached env files there. iirc that variable didn't exist when this project was born, and we tried to have our own directory `dump_dir` where to generate files. I believe we no longer need the later and that would remove the need on using `asdf where direnv`. if anybody could provide a patch for this I'd be awesome since it looks many people also use system direnv.

**Comment by jfly** [comment]
@vic, using `direnv_config_dir` "feels" wrong to me for two reasons:

1. These files we're creating aren't really a direnv thing, they're an asdf-direnv thing.
2. These files aren't configuration, they feel more like a cache to me.

I've put together a PR where I change things to use `XDG_CACHE_HOME`: https://github.com/asdf-community/asdf-direnv/pull/105

**Comment by glasserc** [comment]
It works great! Thank you very much!!
