### ISSUE TITLE
RFC: Drop support for plugin provided direnv in favor of only supporting a system direnv

### ISSUE THREAD

**Issue by jfly** [asdf-community/asdf-direnv#134]
How would folks feel about us dropping support for plugin managed versions of direnv in favor of only supporting a system install?

## Some arguments in favor of this change:

- Supporting two types of installs is always going to be more complicated than one
- People used to asdf and its plugin ecosystem can find this plugin very confusing: it's *not* a tool to let you various projects all use different versions of direnv without stepping on each other's toes. I think the discussion here really captures the confusion element https://github.com/asdf-community/asdf-direnv/discussions/92. Some other examples of confusion:
  - https://github.com/asdf-community/asdf-direnv/issues/103#issue-1160455648: "direnv definitely dispatches to asdf, so having asdf manage direnv too feels a little circular to me" 
  - I personally didn't even know until recently that some of our users use a system managed direnv and that we support it: https://github.com/asdf-community/asdf-direnv/issues/103#issuecomment-1059872183. I switched to a system install of direnv after I learned it's something we support, and I've been even happier with asdf-direnv ever since :)
- It's non-trivial for us to support a plugin managed direnv without falling back on (effectively) running `asdf which` all the time, which we don't want to do because it's slow! @vic has done some awesome work to improve things here, but I think it leaves our users in a bit of a weird state: I don't think any of them would know how to upgrade direnv itself, for instance (I *think* this command would work, but I haven't actually tested it, and we certainly haven't documented it anywhere `asdf direnv setup --version latest`)
  - Even if that `asdf direnv setup` command does work, I don't think it's terribly friendly to give people yet another command they should periodically run to keep their system up to date. Setup feels like something you should only have to do once when first installing our plugin, and maybe we periodically remind you to run it when we make backwards incompatible changes.

## Some arguments against this change:

- We won't be able to give self-contained installation instructions anymore. We'll probably want to point people to https://direnv.net/docs/installation.html, and it's going to be very hard to keep people from getting confused about if they should do step 2 ("hook into your shell")
- Any others?

## How I would make this change

1. Change our setup script to default to a system install of direnv, and update our readme accordingly, mainly that you should first install direnv) 
   - To minimize the likelihood of people double hooking direnv, I propose that our setup script only *check* if direnv is installed and properly hooked into the shell, *but not actually hook direnv into the shell for you*. This will be more work for people setting things up from scratch, but I think this is a more polite thing for us to do: right now, if an existing direnv user wants to start using our tool, they're going to have to remove the direnv hook from their shell config if they want to avoid double hooking direnv)
2. (later) Drop support for plugin managed direnv: simplify our setup script, get rid of the `ASDF_DIRENV_BIN` environment variable, delete our `bin/{install,list-all}` scripts.

**Comment by michi-zuri** [comment]
While I agree with the points you listed in favour, I would be sad about not having the possibility to use asdf provided direnv, because my OS (Solus) doesn't provide a direnv package. I could install it some other way, but I quite enjoyed the ability to pull direnv through asdf.

**Comment by jfly** [comment]
That's good to know, @michi-zuri. I had sort of assumed that any of our users would be covered by the long list here: https://direnv.net/docs/installation.html, but I guess you'd be stuck with the `curl ... | bash` instructions :(

**Comment by vic** [comment]
I'd like to know as many people's opinion on this. I'm no longer an active asdf user myself (actually have it only installed for contributing on this project), so it has become more of a project of yours, it serves to you and I'm happy helping in whatever direction seems to be the most reasonable for users and maintainers.


Regarding `system` version, it was never intended to be supported by this plugin originally. Turns out it was the way asdf has for skipping it's own installed bins. When I used asdf, I had a direnv version set only on my `$HOME/.tool-versions` instead of per-project. I personally never liked installing things system wide, so I tried to install most things with asdf instead of -for example- using brew. So I never installed asdf nor direnv with brew on my system, perhaps because of this I ended up implementing a lot of asdf plugins.

I was quite surprised to find out that many `asdf-direnv` users had a system installation of direnv. So they had to use `asdf global direnv system` for this plugin to work. And perhaps that's what caused much of the confusion, this last step -the one of specifying a system version for asdf- being pointless since they didn't want to install anything, but because this plugin relied on using asdf version resolution from their `.tool-versions` in order to find the direnv executable, it was a necessary step. And the instructions (being written mostly by me) reflected my preferences of installing direnv via asdf.
 
Now, having a direnv selected version on your `.tool-versions` file *was required* before we introduced the `asdf direnv setup` command recently. Since then it's no longer required to even mention direnv on any `.tool-versions` file (nor per-project nor user-default-tool-versions). Not even the `setup` command will write such files in order to define a direnv version. Yet the `setup` command still gives you the opportunity to install direnv via asdf might you not already have one installed.

Perhaps, as many things on humans, it's more about communication. And you (many being native English speakers) can be much better than me on this. Perhaps all we need is be explicit about what choice we recommend on our README (PRs with better grammar welcome):
 
```
If you already have direnv installed run `asdf direnv setup --version system ...`

Otherwise we can install it for you via: `asdf direnv setup --version latest ...`
```

Regarding double direnv shell-hook. I'm mostly sure direnv does create a function for hooking on your prompt-render function or the`cd` command on your shell, we could investigate that function name, and change our `setup` command to check if that function is already defined, then don't eval `direnv hook <shell>`.


Yesterday I dreamed we did remove asdf installation support and another confused issue was created: `What's the point of this being an asdf-plugin if I cannot install direnv with it`. Perhaps it was just a bad dream.

**Comment by jfly** [comment]
Thanks for the feedback! It sounds like there's real value for people to have this plugin be able to install direnv. I think we can close this issue out.

I think there are two followup pieces of work to make things a little more robust:

1. I think we should document how to update asdf-direnv and direnv. I've put together a PR for that here: https://github.com/asdf-community/asdf-direnv/pull/139
2. I think we should change `asdf direnv setup` to detect if direnv is already hooked into the shell somehow. I've filed https://github.com/asdf-community/asdf-direnv/issues/140 to track that.
