### ISSUE TITLE
Question: Is `use asdf` supposed to fail on missing plugins?

### ISSUE THREAD

**Issue by maciej-szlosarczyk** [asdf-community/asdf-direnv#162]
Given the following `.tool-versions`:

```
ruby 3.1.2
nodejs 16.13.0
```

and the following `envrc`:

```
use asdf
```

If I don't have the nodejs plugin, the tool will report `direnv: asdf plugin not installed: nodejs` and exit.  In result, the path to Ruby will be not loaded. Meanwhile, pure asdf will ignore any entries in .tool-versions for which you do not have the plugins and just work for the ones you do.

Is it supposed to work like this?

**Comment by jfly** [comment]
@maciej-szlosarczyk, good question! I *personally* like that it behaves this way (because it ensures that if direnv loads, then I have a working dev environment), but I think we'd have to ask @vic if it's intentional.

Do you want this to behave differently? I could imagine us adding an argument to tweak this behavior (perhaps a `use asdf --no-require-all-plugins`?)

**Comment by maciej-szlosarczyk** [comment]
Hey @jfly, thanks for the answer! I discovered this at work when someone added to `.tool-versions` in a large monorepo a line for `yarn` which I did not use and then `direnv` integration stopped working for me. 

I have a slightly different view. I really like how `asdf` behaves, especially with the number of plugins it supports. For example, we can specify the version of `redis` in your `.tool-versions`, but I am not required to use `asdf` to install it, I can use a docker container instead. `asdf-direnv` does not allow for that flexibility.

_Ideally_ I would retain current behaviour and add ability to load only specific asdf plugins, which would solve my problem:

```bash
use asdf # Loads everything, exits on any missing plugin.
use asdf ruby # Loads only the environment for Ruby, exits on missing Ruby plugin.
```

That being said, I'm perfectly satisfied with `asdf-direnv` not working for me for one specific project.

**Comment by jfly** [comment]
@maciej-szlosarczyk, in your situation, I'd probably just add the yarn asdf plugin, even if I didn't plan to use yarn, just to make things work. Or a lighter weight alternative would be to create a dummy "yarn" plugin that does nothing at all.

That all said, I'd be willing to accept a PR that adds parameters to `use asdf`. How do you feel about something like this?

```
use asdf --only ruby  # Loads only the environment for Ruby, exits on missing Ruby plugin.
```

```
use asdf --ignore yarn  # Loads everything except for Yarn
```

(Which would leave space for other things such as a hypothetical future `use asdf --ignore-uninstalled-plugins`)

What do you think?

**Comment by robsonpeixoto** [comment]
Hi @jfly, I really love this plugin! Thanks for the great job!
I love the default *asdf* behaviour because is simple and can avoid a lot of unnecessary annoying. There are plugins that are very annoying to make works like python and erlang, and if the developer just node a node.js, it will save a lot of time.

About the options `--only` or `--ignore` is not very practical, because in every project the developer will need to choose a different command.

IMHO `--ignore-uninstalled-plugins` or `--ignore-missing-plugins` is a better option.

 

Maybe `use asdf --ignore-missing-plugins` no-require-all-plugins`

**Comment by jfly** [comment]
Yeah, an env var is useful if you want a single knob to affect all your projects.

Alternatively, if you want a single knob that affects all people working in a project, it might be nice to put this in the version controlled envrc file.

I don't think I'll build any of this myself, but would be happy to look at a PR that implements one or more of the ideas we've brainstormed here.

**Comment by robsonpeixoto** [comment]
Hi @jfly ! It is only a draft https://github.com/asdf-community/asdf-direnv/pull/172.
Do you have any feedback?

**Comment by robsonpeixoto** [comment]
#172 is ready for review
