### ISSUE TITLE
Add asdf direnv local command

### ISSUE THREAD

**Issue by imbsky** [asdf-community/asdf-direnv#25]
I don't think it's a bad option to add a command like `asdf direnv local [tool name] [version]` to avoid paying extra cost for the asdf user.

**Comment by imbsky** [comment]
This command creates, for example, the following `.envrc`:

`asdf direnv local nodejs 12.13.0`

```
source $(asdf which direnv_use_asdf)
use asdf nodejs 12.13.0
```

**Comment by vic** [comment]
Actually, I've been thinking of removing the documentation for `use asdf TOOL VERSION` from the README. I guess I'll just move the docs about it as comments to the `use_asdf` function itself.

Most likely `use asdf` (without args) will be the only documented _public usage_ on README.

- `use asdf FILENAME` was a way of loading tools before we supported detecting legacy-file-activated tools and globally-activated tools.
- `use asdf local` and `use asdf global` both are also *private API* and I don't see people having the need to use them directly.
- `use asdf TOOL [VERSION]` is basically *private API* used internally when versions have been determined.

I wouldn't like to add things like `asdf direnv local [tool] [version]`, it would be confusing to have two ways of specifying local versions. (1) `asdf local` and (2) `asdf direnv local`.

IMHO people wouldn't have to specify tools-and-versions *inside* their `.envrc`. That's actually the purpose of the `.tool-versions` file.

So, I believe the only content you'd have to place in your `.envrc` for things to work is just `use asdf`.

Hope this clarifies a bit my position right now.

I'm labeling this as wontfix.

Sidenote: currently it's not possible to add subcommands to asdf, like `asdf foo` or `asdf direnv`, but that would be really nice. As plugins could add extension commands to asdf itself, you could have plugins that only extend or add more commands to asdf, and others like nodejs could provide `asdf nodejs import-release-team-keyring` instead of having people to run `~/.asdf/plugins/nodejs/bin/import-release-team-keyring`. But this is something I'll probably address on a PR to asdf itself.

**Comment by imbsky** [comment]
That makes a lot of sense!
