### ISSUE TITLE
Background thread

### ISSUE THREAD

**Issue by imbsky** [asdf-community/asdf-direnv#5]
If you are added a lot of plugins, the `use_asdf` will cause a wait of a few seconds. Is it possible to load as a background thread? I'm not familiar with direnv, so I don't know if it's possible.

**Comment by vic** [comment]
I guess, there's opportunity for improvement. Currently we simply iterate each tool and dump the environment using a combination of asdf's `with_plugin_env` and `direnv dump`. Each env-dump is  then loaded by `direnv_load`. 

Perhaps using something like gnu parallel, but that would introduce a dependency.

If you notice, there's a line where I'm stripping comments from .tool-versions and also reverse the list at the end. This is because I have a .tool-versions file like:

```
nodejs 12.6.0
graalvm 19.0.2
scala 2.12.10
```

and both `nodejs` and `graalvm` provide executables for `node` however, the one I really want to use is `nodejs`'s. The reason I reverse the list is, the last tool is the first env to be loaded, so that the `nodejs` binaries are first in PATH.

**Comment by imbsky** [comment]
As I said in #6, I don't think many asdf users will use this plugin's direnv feature. So I don't have much resistance to introduce a dependency. What do you think?

**Comment by imbsky** [comment]
The problem is that input is blocked every startup. It would be nice to literally do these things in a separate thread (process?), but I don't have any idea.

**Comment by vic** [comment]
Ok, will try to see what I can do on this tonight :)

**Comment by imbsky** [comment]
Cool, Thanks!
