### ISSUE TITLE
The JAVA_HOME defined prior to cd is lost when asdf java plugin is used 

### ISSUE THREAD

**Issue by iilyak** [asdf-community/asdf-direnv#81]
Steps to reproduce (tested in fish but other people on the team experience same issue on bash)

cat .tool-versions
```
java zulu-7.48.0.11
```

cat .envrc
```
use asdf
```

cat ~/.config/direnv/direnvrc

```
source "$(asdf direnv hook asdf)"
```

cat ~/.config/fish/config.fish

```
source (brew --prefix asdf)/libexec/asdf.fish

# Hook direnv into your shell.
asdf exec direnv hook fish | source
# source (asdf env java get_plugin_path java)/set-java-home.fish

# A shortcut for asdf managed direnv.
function direnv
    asdf exec direnv "$argv"
end
```

```
> set JAVA_HOME=123

> cd test
direnv: loading ~/dev/test/.envrc
direnv: using asdf
direnv: loading ~/.asdf/installs/direnv/2.28.0/env/1885812314-3853398793-854429552-3673295789
direnv: using asdf direnv 2.28.0
direnv: using asdf java zulu-7.48.0.11
direnv: export +JAVA_HOME ~PATH

> echo $JAVA_HOME
/Users/iilyak/.asdf/installs/java/zulu-7.48.0.11

> cd ..
direnv: loading ~/.envrc
direnv: export +DYLD_LIBRARY_PATH +ERL_AFLAGS +MANPATH +REBAR_PLT_DIR +_KERL_ACTIVE_DIR +_KERL_ERL_CALL_REMOVABLE +_KERL_MANPATH_REMOVABLE +_KERL_PATH_REMOVABLE +_KERL_SAVED_ERL_AFLAGS +_KERL_SAVED_REBAR_PLT_DIR ~PATH

> echo $JAVA_HOME
[nothing]
```

**Comment by jfly** [comment]
@iilyak this is happening because of `asdf-java`'s [`exec-env` script](https://github.com/halcyon/asdf-java/blob/master/bin/exec-env). There's some discussion around this over here https://github.com/halcyon/asdf-java/issues/154 and https://github.com/halcyon/asdf-java/pull/148.

I don't do a ton of java development, so I can't image *why* you would want your `JAVA_HOME` to be different than the value that's getting automatically set for you. If you have a legitimate use case for that, perhaps it's worth starting a discussion with the asdf-java folks?

**Comment by jfly** [comment]
@iilyak, I'm going to close this issue. I'd suggest following up with the asdf-java folks if you have more questions.

Happy coding!

**Comment by iilyak** [comment]
I found a workaround which I wanted to share just in case anyone would find it useful.

Add following line into `.envrc`

```shell
export JAVA_HOME="$(dirname "$(dirname "$(expand_path "$(asdf which java)" "/")")")"
```
